[package]
name = "activity_a"
version = "2.3.4"
authors = ["Rettdog <30802926+Rettdog@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
